apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
      - name: reverse-proxy
        image: mini-vercel-proxy:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: AWS_BUCKET_NAME
          value: "mini-vercel-storage-adarsh-1"
        - name: AWS_REGION
          value: "us-east-1"
        # ðŸ‘‡ SECURE SECTION STARTS HERE ðŸ‘‡
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds       # Name of the secret
              key: access-key-id    # Key inside the secret
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: secret-access-key
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  selector:
    app: reverse-proxy
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000