apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: build-server
  template:
    metadata:
      labels:
        app: build-server
    spec:
      containers:
      - name: build-server
        image: mini-vercel-build-server:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379"  # Ensure this matches your Service name
        - name: AWS_BUCKET_NAME
          value: "mini-vercel-storage-adarsh-1"
        - name: AWS_REGION
          value: "us-east-1"
        # ðŸ‘‡ SECURE SECTION STARTS HERE ðŸ‘‡
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds       # Points to the secret you created
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: secret-access-key
        # ðŸ‘† END SECURE SECTION ðŸ‘†

        # ðŸ‘‡ THE MAGIC: Mount the Docker Socket
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock